# -*- coding: utf-8 -*-
"""生成外层引导脚本的最终编码形态: launcher.bat=GBK+CRLF, launcher.sh=UTF-8+LF。

项目的编码铁律:
  *.bat -> GBK + CRLF  (cmd.exe 按 OEM 936 解码, UTF-8 中文会乱码)
  *.sh  -> UTF-8 + LF  (有 CR 则 shebang 报 bad interpreter)
所以源文件一律用 ASCII 逻辑写, 中文只出现在 echo 行(对 bat 而言最终会被编成 GBK)。
"""
import pathlib

BAT = """@echo off
REM ============================================================
REM  Tailscale Remote Toolbox - one click installer
REM  Generated by web console. Keep setup.zip next to this file
REM  and double click. Nothing to type. One UAC prompt max.
REM ============================================================
chcp 936 >nul 2>nul
setlocal enableextensions
cd /d "%~dp0"

set "HERE=%~dp0"
set "ZIP=%HERE%setup.zip"
if not exist "%ZIP%" for %%F in ("%HERE%*.zip") do set "ZIP=%%~fF"

if not exist "%ZIP%" (
  echo.
  echo  [X] setup.zip not found
  echo      Keep setup.zip and this script in the same folder.
  echo.
  pause
  exit /b 1
)

echo.
echo   ==========================================
echo    Tailscale Remote - one click setup
echo   ==========================================
echo.

set "DEST=%TEMP%\\tsr-setup"
if exist "%DEST%" rd /s /q "%DEST%" 2>nul
mkdir "%DEST%" 2>nul

echo  [1/3] Unpacking ...
where tar >nul 2>nul
if %errorlevel%==0 (
  tar -xf "%ZIP%" -C "%DEST%" 2>nul
) else (
  powershell -NoProfile -ExecutionPolicy Bypass -Command "Expand-Archive -LiteralPath '%ZIP%' -DestinationPath '%DEST%' -Force"
)

set "PS1=%DEST%\\tailscale-remote\\install.ps1"
if not exist "%PS1%" set "PS1=%DEST%\\install.ps1"
if not exist "%PS1%" (
  echo  [X] install.ps1 missing inside the zip
  pause
  exit /b 1
)

echo  [2/3] Deploying. If UAC pops up, click Yes ...
echo        The real work runs in the NEW window that opens.
echo.
set "IDIR=%LOCALAPPDATA%\\TailscaleRemote"
powershell -NoProfile -ExecutionPolicy Bypass -File "%PS1%" -InstallDir "%IDIR%" -SourceDir "%HERE%"

echo.
echo  [3/3] Done. The ssh command is in the other window.
echo.
pause
"""

SH = """#!/bin/sh
# ============================================================
#  Tailscale Remote Toolbox - one click installer (Linux)
#  Keep setup.zip next to this file, then:  sh launcher.sh
# ============================================================
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ZIP="$HERE/setup.zip"
if [ ! -f "$ZIP" ]; then ZIP=$(ls "$HERE"/*.zip 2>/dev/null | head -1); fi

if [ -z "$ZIP" ] || [ ! -f "$ZIP" ]; then
  echo ""
  echo "  [X] setup.zip not found - keep it next to this script."
  echo ""
  exit 1
fi

echo ""
echo "  =========================================="
echo "   Tailscale Remote - one click setup"
echo "  =========================================="
echo ""

DEST="$HOME/.cache/tsr-setup"
rm -rf "$DEST"; mkdir -p "$DEST"

echo "  [1/3] Unpacking ..."
if command -v unzip >/dev/null 2>&1; then
  unzip -q -o "$ZIP" -d "$DEST"
elif command -v python3 >/dev/null 2>&1; then
  python3 -c "import zipfile,sys; zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])" "$ZIP" "$DEST"
else
  echo "  [X] need unzip or python3"; exit 1
fi

MAIN="$DEST/tailscale-remote/install.sh"
[ -f "$MAIN" ] || MAIN="$DEST/install.sh"
[ -f "$MAIN" ] || { echo "  [X] install.sh missing"; exit 1; }

echo "  [2/3] Deploying (sudo may ask your password once) ..."
chmod +x "$MAIN" 2>/dev/null || true
if [ "$(id -u)" = "0" ]; then
  sh "$MAIN" --source-dir "$HERE"
elif command -v sudo >/dev/null 2>&1; then
  sudo sh "$MAIN" --source-dir "$HERE"
else
  sh "$MAIN" --source-dir "$HERE"
fi

echo ""
echo "  [3/3] Done."
echo ""
"""

here = pathlib.Path(__file__).parent

p = here / 'launcher.bat'
p.write_bytes(BAT.replace('\n', '\r\n').encode('gbk'))

q = here / 'launcher.sh'
q.write_bytes(SH.encode('utf-8'))

b = p.read_bytes()
b.decode('gbk')
print('launcher.bat  %5d bytes  GBK+CRLF  裸LF=%s' % (len(b), b'\n' in b.replace(b'\r\n', b'')))
s = q.read_bytes()
print('launcher.sh   %5d bytes  UTF-8+LF  裸CR=%s' % (len(s), b'\r' in s))
