@echo off
REM ============================================================
REM  Tailscale Remote Toolbox - one click installer
REM  Generated by web console. Keep setup.zip next to this file
REM  and double click. Nothing to type. One UAC prompt max.
REM ============================================================
chcp 936 >nul 2>nul
setlocal enableextensions
cd /d "%~dp0"

set "HERE=%~dp0"
set "ZIP=%HERE%setup.zip"
if not exist "%ZIP%" for %%F in ("%HERE%*.zip") do set "ZIP=%%~fF"

if not exist "%ZIP%" (
  echo.
  echo  [X] setup.zip not found
  echo      Keep setup.zip and this script in the same folder.
  echo.
  pause
  exit /b 1
)

echo.
echo   ==========================================
echo    Tailscale Remote - one click setup
echo   ==========================================
echo.

set "DEST=%TEMP%\tsr-setup"
if exist "%DEST%" rd /s /q "%DEST%" 2>nul
mkdir "%DEST%" 2>nul

echo  [1/3] Unpacking ...
where tar >nul 2>nul
if %errorlevel%==0 (
  tar -xf "%ZIP%" -C "%DEST%" 2>nul
) else (
  powershell -NoProfile -ExecutionPolicy Bypass -Command "Expand-Archive -LiteralPath '%ZIP%' -DestinationPath '%DEST%' -Force"
)

set "PS1=%DEST%\tailscale-remote\install.ps1"
if not exist "%PS1%" set "PS1=%DEST%\install.ps1"
if not exist "%PS1%" (
  echo  [X] install.ps1 missing inside the zip
  pause
  exit /b 1
)

echo  [2/3] Deploying. If UAC pops up, click Yes ...
echo        The real work runs in the NEW window that opens.
echo.
set "IDIR=%LOCALAPPDATA%\TailscaleRemote"
powershell -NoProfile -ExecutionPolicy Bypass -File "%PS1%" -InstallDir "%IDIR%" -SourceDir "%HERE%"

echo.
echo  [3/3] Done. The ssh command is in the other window.
echo.
pause
